### PR TITLE
remove extra / in url preventing autocomplete from working

### PR DESCRIPTION
**Pull request by marcfor**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
This is not the right place for this fix: this is: https://github.com/open-data/ndm-autocomplete

**Comment by LaurentGoderre** [comment]
Well, you need to change it there first, compile then move it to ndm

**Comment by LaurentGoderre** [comment]
....Unless, @thriuin  would you mind if I moved the grunt config to the ndm and we could compile in place.....

**Comment by thriuin** [comment]
@LaurentGoderre  I'm happy with the way you've set things up, but I like your suggestion to rename the auto-complete project. In future, when time permits, we can think about making both the report generator and the autocomplete separate and generic standalone CKAN projects. I've asked Matt to make a quick doumentation update so that developers will know where to make JS changes. Thanks

**Pull request merged**
