### PR TITLE
Moved the package item display to the WET extension

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Will move this to https://github.com/open-data/ckanext-wet-boew

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@thriuin @wardi any issue with this?

**Comment by thriuin** [comment]
@mattleduc  @LaurentGoderre Not for me - I think all of our application specific customization can be handled by snippets...

**Comment by ghost** [comment]
@LaurentGoderre @thriuin I'm almost certain that this can all be handled via snippets.

**Comment by LaurentGoderre** [comment]
The thing is that I am tackling this already via the WET extension so I don't think this is needed here

**Comment by thriuin** [comment]
I agree, if you can reduce unnecessary duplication, then that's definitely a good thing!

**Pull request merged**
